{"name": "test_add_multiple_students", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/tests/DataDriven/TestData/TestData.xlsx'", "trace": "def test_add_multiple_students():\n        api_url = \"https://thetestingworldapi.com/api/studentsDetails\"\n        f = open(\n            \"D:/python/Python-Codes-master/PyCodes/AUTOMATION_UDEMY/pytest0.2/tests/DataDriven/TestCases/DataFile.json\")\n        json_req = json.loads(f.read())\n    \n        obj = Library.Common(\n            \"/tests/DataDriven/TestData/TestData.xlsx\",\n>           \"Sheet1\")\n\nDataDriven\\TestCases\\TestCases.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nDataDriven\\Library.py:11: in __init__\n    wb = openpyxl.load_workbook(file_name)\n..\\venv\\lib\\site-packages\\openpyxl\\reader\\excel.py:316: in load_workbook\n    data_only, keep_links)\n..\\venv\\lib\\site-packages\\openpyxl\\reader\\excel.py:124: in __init__\n    self.archive = _validate_archive(fn)\n..\\venv\\lib\\site-packages\\openpyxl\\reader\\excel.py:96: in _validate_archive\n    archive = ZipFile(filename, 'r')\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <zipfile.ZipFile [closed]>, file = '/tests/DataDriven/TestData/TestData.xlsx', mode = 'r', compression = 0, allowZip64 = True, compresslevel = None\n\n    def __init__(self, file, mode=\"r\", compression=ZIP_STORED, allowZip64=True,\n                 compresslevel=None):\n        \"\"\"Open the ZIP file with mode read 'r', write 'w', exclusive create 'x',\n        or append 'a'.\"\"\"\n        if mode not in ('r', 'w', 'x', 'a'):\n            raise ValueError(\"ZipFile requires mode 'r', 'w', 'x', or 'a'\")\n    \n        _check_compression(compression)\n    \n        self._allowZip64 = allowZip64\n        self._didModify = False\n        self.debug = 0  # Level of printing: 0 through 3\n        self.NameToInfo = {}    # Find file info given name\n        self.filelist = []      # List of ZipInfo instances for archive\n        self.compression = compression  # Method of compression\n        self.compresslevel = compresslevel\n        self.mode = mode\n        self.pwd = None\n        self._comment = b''\n    \n        # Check if we were passed a file-like object\n        if isinstance(file, os.PathLike):\n            file = os.fspath(file)\n        if isinstance(file, str):\n            # No, it's a filename\n            self._filePassed = 0\n            self.filename = file\n            modeDict = {'r' : 'rb', 'w': 'w+b', 'x': 'x+b', 'a' : 'r+b',\n                        'r+b': 'w+b', 'w+b': 'wb', 'x+b': 'xb'}\n            filemode = modeDict[mode]\n            while True:\n                try:\n>                   self.fp = io.open(file, filemode)\nE                   FileNotFoundError: [Errno 2] No such file or directory: '/tests/DataDriven/TestData/TestData.xlsx'\n\nC:\\python35\\lib\\zipfile.py:1207: FileNotFoundError"}, "start": 1659022326101, "stop": 1659022326102, "uuid": "79c2e1d8-5753-4b4c-997b-d0cc54ec1145", "historyId": "f4ee5d3714603908355a8871f1076731", "testCaseId": "19bac2bc630b53b4d69777f6663155ac", "fullName": "tests.DataDriven.TestCases.TestCases#test_add_multiple_students", "labels": [{"name": "parentSuite", "value": "tests.DataDriven.TestCases"}, {"name": "suite", "value": "TestCases"}, {"name": "host", "value": "131921-T480"}, {"name": "thread", "value": "16000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.DataDriven.TestCases.TestCases"}]}